### ISSUE TITLE
Countries of birth missing ‘Born elsewhere(e)’ and ‘Country of Birth not stated’ 

### ISSUE THREAD

**Issue by carmelachivers1** [HughParsonage/Census2016#2]
The countries of birth data is missing ‘Born elsewhere(e)’ and ‘Country of Birth not stated’, which could lead to misinterpretations. 

The list also only includes the top 35 countries of birth for Australia overall, which may erase regional variations.

**Comment by HughParsonage** [comment]
Thanks for the report! I'll update the documentation.

The information from columns `Born elsewhere(e)` and `Country of Birth not stated` may nonetheless be present in this package:

Vide: https://github.com/nickjevershed/census-scraper-2016/blob/master/scraper.py#L157

That is, the column `born_overseas` in `Census2016_wide_by_SA2_year` includes the residual.
